---
title: "CB[1], Latin Square, SP/RM[1,1]"
author: "Randi Garcia"
output:
  html_document:
  theme: cerulean
highlight: pygments
css: ../lab.css
toc: true
toc_float: true
---
  
```{r global-options, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
library(dplyr)
library(lattice)
library(ggplot2)
library(tidyr)
library(dae)
library(mosaic)
library(knitr)
```

# Complete Block Design

```{r}
tree <- c(rep("tree1",3), rep("tree2",3), rep("tree3", 3),rep("tree4", 3), rep("tree5", 3))
treatment <- rep(c("water", "spores", "oil"), 5)
bugs_change <- c(-9, -4, 4, 18, 29, 29, 10, 4, 14, 9, -2, 14, -6, 11, 7)

mealybugs <- data.frame(tree, treatment, bugs_change)
```


```{r}
mod <- lm(bugs_change ~ treatment + tree, data = mealybugs)

anova(mod)
```

## Informal Analysis

```{r}
mealybugs_wide <- mealybugs %>%
  spread(treatment, bugs_change)

ggplot(mealybugs_wide, aes(x = spores, y = oil)) +
  geom_point()
```

```{r}
ggplot(mealybugs_wide, aes(x = spores, y = water)) +
  geom_point()
```

```{r}
ggplot(mealybugs_wide, aes(x = oil, y = water)) +
  geom_point()
```

# Latin Square

```{r}
subject <- c(rep("1",3), rep("2",3), rep("3", 3))
treatment <- c("solution(A)", "capsule(C)", "tablet(B)",
               "capsule(C)", "tablet(B)", "solution(A)",
               "tablet(B)", "solution(A)", "capsule(C)")
period <- rep(c("1", "2", "3"),3)
concentration <- c("A 1799", "C 1846", "B 2147", "C 2075", "B 1156", "A 1777",
                   "B 1396", "A 868", "C 2291")

bioequivalence <- data.frame(subject, treatment, period, concentration)

bioequivalence %>%
  select(-treatment) %>%
  spread(subject, concentration)
```

