---
title: "Data Ethics Resources"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

Thank you to **Julie Destine** for putting these resources together for us!! She also co-authored this website page. 

Credit also to three people who served as a starting point for these resources: Albert Kim, Hannah Snell, and Audrey Bertin. Thank you to Albert for sharing some of the materials that he discusses with his class. Hannah and Audrey have a website called [Data Science Resources for Change](https://hmsnell.github.io/DataSci-ResourcesForChange/). Great site, Hannah and Audrey, thank you!

***

  1. Ethical collection of human subjects data
      - [Video](https://www.youtube.com/watch?v=CzNANZnoiRs)
        - This one is nice because it introduces the question of how we might apply the principals you learned in your CITI training. to the social media/technology space.  
  2. [Fisher](https://en.wikipedia.org/wiki/Ronald_Fisher#Eugenics) (ANOVA inventor) and Eugenics 
      - [Call to Remove Fisher's name from award](https://twitter.com/daniela_witten/status/1268392721275744256?s=09)
      - [Eugenics and Francis Galton](https://www.youtube.com/watch?v=JeCKftkNKJ0)
        - Galton had a lot of impact on the world of statistics but consider the effects it had on people.
      - [Learning for Justice](https://www.learningforjustice.org/magazine/how-samuel-morton-got-it-wrong) and p.115 of textbook talk about Samuel Morton.
      - What happens when a good thing comes from someone who did wrong? 
        - Another example: [Buzzfeed's Article on DataCamp](https://www.buzzfeednews.com/article/daveyalba/datacamp-sexual-harassment-metoo-tech-startup)
  3. P-hacking  
      - [Article](https://www.wired.com/story/were-all-p-hacking-now/)
      - [Video](https://www.youtube.com/watch?v=Gx0fAjNHb1M)
      - [P-hacking and jelly beans](https://xkcd.com/882/)
  4. Ethics of collaboration  
      - [Resources for Research Ethics Education](http://research-ethics.org/topics/research-misconduct/#summary)
      - [Example scenario](https://statmodeling.stat.columbia.edu/2017/11/11/student-bosses-want-p-hack-dont-even-know/) 
      - [Rebekah Jones](https://statmodeling.stat.columbia.edu/2017/11/11/student-bosses-want-p-hack-dont-even-know/) and the ethics of reporting COVID numbers (thank you to Angela Jauregui for sharing)
  5. Ethics and Social Media 
      - [The Social Dilemma](https://www.youtube.com/watch?v=uaaC57tcci0) (Netflix documentary trailer)
      - [The Great Hack](https://www.youtube.com/watch?v=iX8GxLP1FHo) (Netflix documentary trailer)
 
***

