---
title: "Schedule"
---

Please read the specified sections *before* class that day. 

<div class="past">
</div> <!--closing "past" div-->


<div class="row">
  <div class="col-md-3 past">
#### Tue, Aug 31
+ No class
  </div>
  
  <div class="col-md-3 past">
#### Wed, Sep 1
+ No class
  </div>
  
  <div class="col-md-3 past">
#### Thurs, Sep 2
+ Introduction to the course
+ Four-step process
+ [Short experiment](https://smithcollege.qualtrics.com/jfe/form/SV_71nqdhEpN8frd6B)
+ Homework:
    + HW #1a: record your name on Moodle
    + HW #1b: CITI training
  </div>
  
  <div class="col-md-3 past">
#### Fri, Sep 3
+ Homework due today:
    + Read **Stat2** Ch. 0 (PDF on Moodle)
    + **HW #1a due today at 11:55p**
  </div>
  
</div>

***

<div class="row">
  <div class="col-md-3 past">
#### Tue, Sep 7
+ One-way ANOVA
+ Homework due today:
    + Read **Stat2** Ch. 5.1-5.2
  </div>
  
  <div class="col-md-3 past">
#### Wed, Sep 8
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3 past">
#### Thurs, Sep 9
+ One-way ANOVA (cont.)
+ Homework due today:
  + Read **Stat2** Ch. 5.3 
+ Office hours: 1:20-2:35p    
  </div>
  
  <div class="col-md-3 past">
#### Fri, Sep 10
+ Homework due today:
    + **HW #1b and #1c due today at 11:55p**
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)    
  </div>
</div>

***

<div class="row">
  <div class="col-md-3 past">
#### Tue, Sep 14
+ Inference for ANOVA
+ Homework due today:
  + Read **Stat2** Ch. 5.4 
  </div>
  
  <div class="col-md-3 past">
#### Wed, Sep 15
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3 past">
#### Thurs, Sep 16
+ ANOVA Conditions
+ MP1 assignment
+ Homework due today:
  + No reading for today
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3 past">
#### Fri, Sep 17
+ Homework due today:
    + **HW #2 due today at 11:55p**
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)      
  </div>
</div>

***

<div class="row">
  <div class="col-md-3 past">
#### Tue, Sep 21
+ Confidence intervals and effect sizes
+ Transformations 
+ MP1 topics
+ Homework due today:
  + Brainstorm topics for MP1
  + Read **Stat2** Ch. 5.5-5.6
  </div>
  
  <div class="col-md-3 past">
#### Wed, Sep 22
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Sep 23
+ Multiple comparisons
+ Introduction to Qualtrics
+ Homework due today:
    + Find potential stimuli (images) for MP1
    + Read **Stat2** 4.5 (up to, not including, example 4.10)
    + Read **Stat2** 5.7
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Sep 24
+ Homework due today:
  + **HW #3 due on today at 11:55p**
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)    
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Sep 28
+ Four basic designs
+ Time to work on MP1
+ Homework due today:
    + Read **Cobb** Ch. 1.1-1.3 (PDF on Moodle)
  </div>
  
  <div class="col-md-3">
#### Wed, Sep 29
+ Office hours **on Zoom only**: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Sep 30
+ **Class cancelled**
+ Office hours **on Zoom only**: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Oct 1
+ Homework due today:
  + **HW #4 due on today at 11:55p**
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)    
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Oct 5
+ Blocking
+ Homework due today:
    + Read **Stat2** Ch 6.1-6.2
  </div>
  
  <div class="col-md-3">
#### Wed, Oct 6
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Oct 7
+ Fitting the model for a block design
+ Homework due today:
    + Read Ch **Stat2** 6.3
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Oct 8
+ Homework due today:
    + **MP1 Qualtrics survey due for pre-approval by 11:55p**
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)  
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Oct 12
+ **Fall break**
  </div>
  
  <div class="col-md-3">
#### Wed, Oct 13
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Oct 14
+ MP1 Data Collection Day
+ Assessing the block design
+ Using the block design
+ Homework due today:
    + Read Ch **Stat2** 6.4-6.5
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Oct 15
+ Homework due today:
    + **HW #5 due tonight at 11:55p**
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)      
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Oct 19
+ Review for Exam 1
+ Work on MP1
  </div>
  
  <div class="col-md-3">
#### Wed, Oct 20
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Oct 21
+ *Time to work on Exam 1**
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Oct 22
+ Homework due today:
    + **Exam 1 due tonight at 11:55p**
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)      
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Oct 26
+ Interactions
+ Two-way factorial designs
+ Homework due today:
    + Read Ch **Stat2** 7.1-7.3
  </div>
  
  <div class="col-md-3">
#### Wed, Oct 27
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Oct 28
+ Fitting two-way ANOVA
+ Practice designs
+ Homework due today:
    + Read Ch **Stat2** 7.4
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Oct 29
+ Homework due today:
    + **Mini Project 1 due 11:55p** (upload to Moodle by Midnight)
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)  
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Nov 2
+ Assessing two-way design
+ Practice designs
+ Homework due today:
    + Read Ch **Stat2** 7.5

  </div>
  
  <div class="col-md-3">
#### Wed, Nov 3
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Nov 4
+ **Cromwell Day - Class cancelled**
+ **Office hours cancelled**
  </div>
  
  <div class="col-md-3">
#### Fri, Nov 5
+ Homework due today:
    + [**HW #6 due today at 11:55p**](homework.html) 
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)      
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Nov 9
+ Using two-way design
+ Practice designs
+ Homework due today:
    + Read Ch **Stat2** 7.6
  </div>
  
  <div class="col-md-3">
#### Wed, Nov 10
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Nov 11
+ Test for homogeneity of variance
+ Multiple tests
+ Comparisons and contrasts
+ Homework due today:
    + Read Ch **Stat2** 8.1-8.3
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Nov 12
+ Homework due today:
    + [**HW #7 due thurs at 11:55p**](homework.html)
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)      
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Nov 16
+ Ethics
+ Nonparametric tests
+ Homework due today:
    + Read Ch **Stat2** 8.4
    + [Fisher's history of racism](https://en.wikipedia.org/wiki/Ronald_Fisher#Eugenics)
  </div>
  
  <div class="col-md-3">
#### Wed, Nov 17
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Nov 18
+ Randomization F-tests
+ Homework due today:
    + Read Ch **Stat2** 8.5
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Nov 19
+ Homework due today:
    + [**HW #8 due today at 9:20a**](homework.html)
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)      
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Nov 23
+ Repeated measures designs
+ Homework due today:
    + Read Ch **Stat2** 8.6
  </div>
  
  <div class="col-md-3">
#### Wed, Nov 24
+ **Thanksgiving break**
  </div>
  
  <div class="col-md-3">
#### Thurs, Nov 25
+ **Thanksgiving break**
  </div>
  
  <div class="col-md-3">
#### Fri, Nov 26
+ **Thanksgiving break**
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Nov 30
+ Repeated measures designs
+ Homework due today:
    + Read Ch **Stat2** 8.6
  </div>
  
  <div class="col-md-3">
#### Wed, Dec 1
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Dec 2
+ ANOVA with indicator variables
+ ANCOVA
+ Homework due today:
    + Read Ch **Stat2** 8.7-6.8
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Dec 3
+ Homework due today:
    + [**HW #9 due today at 9:20a**](homework.html)
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)      

  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Dec 7
+ Review for Exam 2
  </div>
  
  <div class="col-md-3">
#### Wed, Dec 8
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Dec 9
+ **Exam 2 work time**
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Dec 10
+ Homework due today:
    + **Exam 2 due tonight at 11:55p**
+ Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)  
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Tue, Dec 14
+ **Finals week**
  </div>
  
  <div class="col-md-3">
#### Wed, Dec 15
+ Office hours: 10:50-12:05p
  </div>
  
  <div class="col-md-3">
#### Thurs, Dec 16
+ Office hours: 1:20-2:35p
  </div>
  
  <div class="col-md-3">
#### Fri, Dec 17
+ **MP2 due today at 11:55p**

  </div>
</div>

    